# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven (Java 12)

on:
  push:
    branches:
      - main
      - '*-SNAPSHOT'
  pull_request:
    # The branches below must be a subset of the branches above
    branches:
      - main
      - '*-SNAPSHOT'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 12
      uses: actions/setup-java@v1
      with:
        java-version: 12.0.1
    - name: Build with Maven
      run: ./mvnw --batch-mode verify --file pom.xml
